volumes:
  data-postgresql:
    driver: local
  data-postgresql-archives:
    driver: local

services:
  payment-integration:
    container_name: virail.payment.integration
    build:
      context: ./docker/payment-integration/
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - './:/home/payment-integration/'
      - .config/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "${PAYMENT_INTEGRATION_LISTEN:-0.0.0.0:8080:80}"
    env_file:
      - ${PAYMENT_INTEGRATION_ENV_FILE:-.env}
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

  postgresql:
    image: postgis/postgis
    container_name: virail.pa.postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}
    shm_size: '2gb'
    volumes:
      - ./.psql_history:/root/.psql_history
      - data-postgresql:/var/lib/postgresql/data
      - data-postgresql-archives:/archives/
    ports:
      - ${POSTGRES_LISTEN:-127.0.0.1:5432:5432}
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}