volumes:
  data-postgresql:
    driver: local
  data-postgresql-archives:
    driver: local

services:
  payment-integration:
    container_name: virail.payment.integration
    build:
      context: ./docker/payment-integration/
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - './:/home/payment-integration/'
      - .config/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "${PAYMENT_INTEGRATION_LISTEN:-0.0.0.0:8080:80}"
    env_file:
      - ${PAYMENT_INTEGRATION_ENV_FILE:-.env}
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}